# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SaveTheVineyard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SaveTheVineyard
   pod 'Firebase/Core'
   pod 'FirebaseStorage'
   pod 'FirebaseDatabase'
   pod 'Toaster'
   pod 'Firebase/Auth'

end
